name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Or your primary branch, e.g., master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      id: build-and-push
      run: |
        IMAGE_PATH="${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO}}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}"
        docker build -t $IMAGE_PATH .
        docker push $IMAGE_PATH
        echo "image_path=$IMAGE_PATH" >> $GITHUB_OUTPUT

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image ${{ steps.build-and-push.outputs.image_path }}\
          --set-env-vars "DB_USER=${{ secrets.DB_USER }},DB_PASS=${{ secrets.DB_PASS }},DB_NAME=${{ secrets.DB_NAME }},DB_HOST=${{ secrets.DB_HOST }}" \
          --platform managed \
          --region ${{ secrets.ARTIFACT_REGISTRY_LOCATION }} \
          --allow-unauthenticated \
          --project=${{ secrets.GCP_PROJECT_ID }}
